### ISSUE TITLE
Powershell shows path, context not correct

### ISSUE THREAD

**Issue by niv0** [paulbouwer/k8s-cli-toolset#4]
German(Austrian) Windows 10, Powershell 

Here how it looks like:
<img width="620" alt="Unbenannt" src="https://user-images.githubusercontent.com/2017626/79553560-f4e31e00-809c-11ea-92c6-b355425ca430.png">

I launched the container with

docker run -it --rm -v ${home}\.kube:/root/.kube -v ${home}\.helm:/root/.helm paulbouwer/k8s-cli-toolset:0.15

**Comment by paulbouwer** [comment]
[Kubie](https://github.com/sbstp/kubie) is now part of this image - I no longer include `kubectx` and `kubens`. Have a look at the kubie documentation to understand how to use it to change clusters and namespaces.

**Comment by paulbouwer** [comment]
Closing.
